#!/usr/bin/env python3
"""
export_weights_v2.py — Export models_v2 weights + scaler as a C++ header.

Run once after training (or whenever the model is retrained):
  cd /path/to/ML
  python export_weights_v2.py

Output: ../ESP32 Code/include/hive_model_v2_weights.h
"""

import os
import sys
import numpy as np

BASE      = os.path.dirname(os.path.abspath(__file__))
MODEL_DIR = os.path.join(BASE, "models_v2")
OUT_PATH  = os.path.join(os.path.dirname(BASE), "ESP32 Code", "include",
                         "hive_model_v2_weights.h")

sys.path.insert(0, BASE)

import joblib
from model import HiveNet  # noqa: F401 — needed for joblib unpickling

model  = joblib.load(os.path.join(MODEL_DIR, "hive_model.pkl"))
scaler = joblib.load(os.path.join(MODEL_DIR, "scaler.pkl"))

sd = model.state_dict()

# HiveNet Sequential indices:
# 0: Linear(N, 32)   1: ReLU   2: Dropout
# 3: Linear(32, 16)  4: ReLU   5: Dropout
# 6: Linear(16, 1)   7: Sigmoid
w1 = sd["net.0.weight"].numpy()           # [32, 16]
b1 = sd["net.0.bias"].numpy()             # [32]
w2 = sd["net.3.weight"].numpy()           # [16, 32]
b2 = sd["net.3.bias"].numpy()             # [16]
w3 = sd["net.6.weight"].numpy().flatten() # [16]  (was [1, 16])
b3 = float(sd["net.6.bias"].numpy()[0])   # scalar

scaler_mean  = scaler.mean_.astype(np.float64)
scaler_scale = scaler.scale_.astype(np.float64)

n_in, h1, h2 = w1.shape[1], w1.shape[0], w2.shape[0]
print(f"Architecture: {n_in} → {h1} → {h2} → 1")
print(f"Scaler mean  range : [{scaler_mean.min():.4f}, {scaler_mean.max():.4f}]")
print(f"Scaler scale range : [{scaler_scale.min():.4f}, {scaler_scale.max():.4f}]")


def c_array_2d(name, arr, rows, cols):
    lines = [f"static const float {name}[{rows}][{cols}] = {{"]
    for i in range(rows):
        row = ", ".join(f"{arr[i, j]:.8f}f" for j in range(cols))
        lines.append(f"    {{{row}}},")
    lines.append("};")
    return "\n".join(lines)


def c_array_1d(name, arr):
    vals = ", ".join(f"{v:.8f}f" for v in arr)
    return f"static const float {name}[{len(arr)}] = {{{vals}}};"


lines = [
    "#pragma once",
    "// Auto-generated by ML/export_weights_v2.py — do not edit manually.",
    "",
    f"#define HVM2_N_IN  {n_in}",
    f"#define HVM2_H1    {h1}",
    f"#define HVM2_H2    {h2}",
    "",
    "// Layer 1 weights & biases",
    c_array_2d("HVM2_W1", w1, h1, n_in),
    c_array_1d("HVM2_B1", b1),
    "",
    "// Layer 2 weights & biases",
    c_array_2d("HVM2_W2", w2, h2, h1),
    c_array_1d("HVM2_B2", b2),
    "",
    "// Output layer weights & bias",
    c_array_1d("HVM2_W3", w3),
    f"static const float HVM2_B3 = {b3:.8f}f;",
    "",
    "// StandardScaler parameters (applied after per-hive z-score)",
    c_array_1d("HVM2_SCALER_MEAN",  scaler_mean),
    c_array_1d("HVM2_SCALER_SCALE", scaler_scale),
]

os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
with open(OUT_PATH, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"\nWrote {OUT_PATH}")
print(f"File size: {os.path.getsize(OUT_PATH):,} bytes")
