#!/usr/bin/env python3
"""
gen_inference_testvecs.py — Generate C++ test vectors for hive_inference.h.

Strategy: synthesize z-scored feature vectors (as if per-hive baseline has
been applied), then apply StandardScaler → model. In C++ the test sets
fused_mean=SCALER_MEAN and fused_scale=SCALER_SCALE (bypassing per-hive
z-score, equivalent to hive_mean=0 / hive_std=1).

Usage: cd ML && python gen_inference_testvecs.py
"""

import os, sys
import numpy as np
import torch

BASE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE)

import joblib
from model import HiveNet  # noqa: F401

model  = joblib.load(os.path.join(BASE, "models_v2", "hive_model.pkl"))
scaler = joblib.load(os.path.join(BASE, "models_v2", "scaler.pkl"))
model.eval()

N = 16  # HVM2_N_IN

def infer_zscored(feat_zscored: np.ndarray) -> tuple[float, np.ndarray]:
    """Apply StandardScaler then run model on already-z-scored features."""
    x_scaled = scaler.transform(feat_zscored.reshape(1, -1)).astype(np.float32)
    with torch.no_grad():
        prob = float(model(torch.FloatTensor(x_scaled)).squeeze())
    return prob, x_scaled.flatten()


# ── Scenarios: values are in z-scored space (mean≈0, std≈1 per feature) ──────
rng = np.random.default_rng(0)

scenarios = {
    # Healthy: all features near 0 (close to hive baseline)
    "HEALTHY_NORMAL":  rng.normal(0.0, 0.4, N).astype(np.float32),
    # Healthy: slightly cooler than baseline
    "HEALTHY_COOL":    rng.normal(-0.5, 0.3, N).astype(np.float32),
    # Stressed: high z-scores on temperature and humidity (well above baseline)
    "STRESSED_HOT":    np.clip(rng.normal(3.5, 0.5, N), 2.0, 6.0).astype(np.float32),
    # Borderline: moderate elevation
    "BORDERLINE":      rng.normal(1.5, 0.4, N).astype(np.float32),
}

results = {}
for name, feat in scenarios.items():
    prob, scaled = infer_zscored(feat)
    results[name] = {"raw": feat, "scaled": scaled, "prob": prob}
    print(f"  {name}: prob={prob:.4f}")

print()
print("// ── auto-generated by ML/gen_inference_testvecs.py ──────────────────────────")
print("// 'raw' vectors are already z-scored. C++ test must set:")
print("//   wf.fused_mean[i]  = HVM2_SCALER_MEAN[i]")
print("//   wf.fused_scale[i] = HVM2_SCALER_SCALE[i]")
print("//   wf.done = true")
print()
print(f"static const int TV_N = {len(scenarios)};")
print("static const char *TV_NAMES[] = {")
for name in scenarios:
    print(f'    "{name}",')
print("};")
print()
print("// Input features (z-scored, before StandardScaler)")
print(f"static const float TV_ZSCORED[TV_N][HVM2_N_IN] = {{")
for name, r in results.items():
    vals = ", ".join(f"{v:.8f}f" for v in r["raw"])
    print(f"    {{{vals}}},  // {name}")
print("};")
print()
print("// Expected model probability (tolerance ±0.0001f)")
print(f"static const float TV_EXPECTED_PROB[TV_N] = {{")
for name, r in results.items():
    print(f"    {r['prob']:.8f}f,  // {name}")
print("};")
